version: '3.9'

services:
  db:
    image: postgres:16
    container_name: pg
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: api
    env_file:
      - .env                # usa el .env de la raíz (con host db)
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: "America/Bogota"

volumes:
  pgdata:
